<?php ?>
<div class="container facilidades">
	
	<div class="left double-left">
	<p class="blue">www.somosbelcorp.com</p>
	<p class="blue big">¡Hace tu negocio más fácil!</p>

		<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque nec diam quis sapien aliquet blandit. Sed pulvinar tincidunt diam, molestie viverra tortor commodo in.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque nec diam quis sapien aliquet blandit. Sed pulvinar tincidunt diam, molestie viverra tortor commodo in.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque nec diam quis sapien aliquet blandit. Sed pulvinar tincidunt diam, molestie viverra tortor commodo in.</p>
		<div class="left" style="width:270px; margin-top:25px;">
		<h3 class="facil">Pase de Pedido Web</h3>
		<img src="<?php echo $this->getSkinUrl('images/facil_1.jpg') ?>" alt="" />
		</div>
		<div class="left" style="width:300px; margin-left:30px; margin-top:25px;">
		<h3 class="facil2">Enviar Catálogos Virtuales</h3>
		<img src="<?php echo $this->getSkinUrl('images/facil_2.jpg') ?>" alt="" />
		</div>
		
	</div>
	<div class="right double-right">
		
		<h3>Otros Beneficios</h3>
		<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque nec diam quis sapien aliquet blandit. Sed pulvinar tincidunt </p>
		<a href="<?php echo $this->getUrl('productos.html');?>" class="productos-link1 pro-a">Productos</a>
		<a href="<?php echo $this->getUrl('ganancias.html');?>" class="productos-link2 pro-a">Ganancias</a>
		<a href="<?php echo $this->getUrl('facilidades.html');?>" class="productos-link3 pro-a">Facilidades</a>
		<a href="<?php echo $this->getUrl('testimonios.html');?>" class="productos-link4 pro-a">Testimonios</a>
		
		
					</div>
	
</div>