<?php ?>
<div class="container ganancias">
	
	<div class="left double-left">
		<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque nec diam quis sapien aliquet blandit. Sed pulvinar tincidunt diam, molestie viverra tortor commodo in.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque nec diam quis sapien aliquet blandit. Sed pulvinar tincidunt diam, molestie viverra tortor commodo in.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque nec diam quis sapien aliquet blandit. Sed pulvinar tincidunt diam, molestie viverra tortor commodo in.</p>
		<div class="left" style="width:250px;">
		<img src="<?php echo $this->getSkinUrl('images/revista.jpg') ?>" alt="" />
		<img src="<?php echo $this->getSkinUrl('images/catalogos.jpg') ?>" alt="" />
		</div>
		<div class="left" style="width:200px;">
		<img src="<?php echo $this->getSkinUrl('images/gana.jpg') ?>" alt="" />
		</div>
		
	</div>
	<div class="right double-right">
		
		<h3>Otros Beneficios</h3>
		<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque nec diam quis sapien aliquet blandit. Sed pulvinar tincidunt </p>
		<a href="<?php echo $this->getUrl('productos.html');?>" class="productos-link1 pro-a">Productos</a>
		<a href="<?php echo $this->getUrl('ganancias.html');?>" class="productos-link2 pro-a">Ganancias</a>
		<a href="<?php echo $this->getUrl('facilidades.html');?>" class="productos-link3 pro-a">Facilidades</a>
		<a href="<?php echo $this->getUrl('testimonios.html');?>" class="productos-link4 pro-a">Testimonios</a>
		
		
					</div>
	
</div>