<?php ?>
<div class="container gracias">
	
	<div class="left double-left">
		<p class="blue big">Gracias por unirte a Belcorp<p>
		<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque nec diam quis sapien <br/>aliquet blandit. Sed pulvinar tincidunt diam, molestie viverra tortor commodo in.<br/>Lorem ipsum dolor sit amet, consectetur adipiscing elit. </p>
		
		<p class="middle purple">Recomienda y Comparte</p><p class="middle blue">esta oportunidad de negocio</p>
		<p class="middle">Difunde y comparte tu experiencia con más personas, <br/>que desean unirse a Belcorp y cambiar sus vidas.</p>
				
		<ul class="social">
			<li class="correo"><a href="#">Correo</a></li>
			<li class="fb"><a href="#">Facebook</a></li>
			<li class="tw"><a href="#">Twitter</a></li>
			
		</ul>
	</div>
	<div class="right double-right">
		
		<h3>Contacto</h3>
		<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam. Sed nisi. Nulla quis sem at nibh elementum imperdiet. Duis sagittis ipsum.</p>
		<h4>Lista de teléfonos de contácto</h4>
		<ul class="contact-list">
			<li>Argentina: <span>0800-888-523</span></li>
			<li>Bolivia: <span>0800-888-523</span></li>
			<li>Chile: <span>0800-888-523</span></li>
			<li>Colombia: <span>0800-888-523</span></li>
			<li>Costa Rica: <span>0800-888-523</span></li>
			<li>Dominicana: <span>0800-888-523</span></li>
			<li>Ecuador: <span>0800-888-523</span></li>
			<li>El Salvador: <span>0800-888-523</span></li>
			<li>Guatemala: <span>0800-888-523</span></li>
			<li>Mexico: <span>0800-888-523</span></li>
			<li>Panama: <span>0800-888-523</span></li>
			<li>Peru: <span>0800-888-523</span></li>
			<li>Venezuela: <span>0800-888-523</span></li>

		</ul>
	</div>
	
</div>