<?php ?>
<div class="container marcas">
	
	<div class="marca mar1">
		<img class="brand" src="<?php echo $this->getSkinUrl('images/marcas_lbel.jpg') ?>" alt="" />
			<p>Investiga para innovar constantemente<br/> en lineas de tratamiento facial y<br/>maquillaje; para que toda mujer<br/>
			pueda tener una piel sin edad,<br/> a cualquier edad.</p>
			<img src="<?php echo $this->getSkinUrl('images/lbel_img.png') ?>" alt="" />

	</div>	
	
	<div class="marca mar2">
		
		<img class="brand" src="<?php echo $this->getSkinUrl('images/marcas_esika.jpg') ?>" alt="" />
		<p>Una amplia selección de aromas, color, <br/>productos de belleza y cuidado para la <br/>mujer y su familia. <br/>La mas alta calidad a muy buen precio.</p>
		<img src="<?php echo $this->getSkinUrl('images/esika_img.png') ?>" alt="" />
	</div>	
	
	<div class="marca mar3">
		<img class="brand" src="<?php echo $this->getSkinUrl('images/marcas_cyzone.jpg') ?>" alt="" />
		<p>Maquillaje, fragancias, ropa y<br/> accesorios exclusivamente para<br/> jóvenes.</p>
		<img src="<?php echo $this->getSkinUrl('images/cyzone_img.png') ?>" alt="" />
		
	</div>	
	
</div>