<?php ?>
<div class="container negocio">
	
	<div class="left double-left">
	<p class="blue">Con Belcorp</p>
	<p class="blue big">lo tienes todo!</p>
	
	<h3 class="mas-1">Más Productos</h3>
	<p>
		3 marcas con más de 700 productos para todos los gustos<br/>
	150 productos nuevos cada año.</p>
		
	<h3 class="mas-2">Más Ganancias</h3>
	<p>
		Hasta 70% de descuento en<br/>
productos de tu Revista Gana. Hasta 40% de descuento en<br/>
productos de los 3 catálogos. Atractivos premios por tus logros.
	</p>
	
	<h3 class="mas-3">Más Facilidades</h3>
	<p>Dupla Cyzone<br/>
		Supérate con Belcorp<br/>
		Guía y orientación constante en:<br/>
		<a href="http://www.somosbelcorp.com" target="_blank"><span class="somos">www.somosbelcorp.com</span></a></p>
		
	</div>
	<div class="right double-right">
		
		<h3>Contacto</h3>
		<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam. Sed nisi. Nulla quis sem at nibh elementum imperdiet. Duis sagittis ipsum.</p>
		<h4>Lista de teléfonos de contácto</h4>
		<ul class="contact-list">
			<li>Argentina: <span>0800-888-523</span></li>
			<li>Bolivia: <span>0800-888-523</span></li>
			<li>Chile: <span>0800-888-523</span></li>
			<li>Colombia: <span>0800-888-523</span></li>
			<li>Costa Rica: <span>0800-888-523</span></li>
			<li>Dominicana: <span>0800-888-523</span></li>
			<li>Ecuador: <span>0800-888-523</span></li>
			<li>El Salvador: <span>0800-888-523</span></li>
			<li>Guatemala: <span>0800-888-523</span></li>
			<li>Mexico: <span>0800-888-523</span></li>
			<li>Panama: <span>0800-888-523</span></li>
			<li>Peru: <span>0800-888-523</span></li>
			<li>Venezuela: <span>0800-888-523</span></li>

		</ul>
	</div>
	
</div>