<?php ?>
<div class="container quees">
	
	<div class="left double-left">
		<p style="margin-top:0px;"><span class="purple">Belcorp</span> es una corporación comprometida con la<br/>
belleza y realización personal<br/>
de la mujer.<p>

<p>Más de 900,000 mujeres en 16 países confían en nosotros y<br/> tienen su propio negocio como Consultoras, lo que les ha<br/> permitido crecer a nivel personal y profesional.</p>

<p>Con Belcorp tendrás la oportunidad de alcanzar todos tus <br/>sueños, meta tras meta.<br/>
Te damos la fuerza de nuestras 3 marcas ganadoras: L’Bel, <br/>Ésika y Cyzone.

</p>
<p class="blue">¡Es momento de creer en ti</p>
	<p class="blue big">y lograrlo todo!</p>
</p>
		
	</div>
	<div class="right double-right">
		
		<h3>Contacto</h3>
		<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam. Sed nisi. Nulla quis sem at nibh elementum imperdiet. Duis sagittis ipsum.</p>
		<h4>Lista de teléfonos de contácto</h4>
		<ul class="contact-list">
			<li>Argentina: <span>0800-888-523</span></li>
			<li>Bolivia: <span>0800-888-523</span></li>
			<li>Chile: <span>0800-888-523</span></li>
			<li>Colombia: <span>0800-888-523</span></li>
			<li>Costa Rica: <span>0800-888-523</span></li>
			<li>Dominicana: <span>0800-888-523</span></li>
			<li>Ecuador: <span>0800-888-523</span></li>
			<li>El Salvador: <span>0800-888-523</span></li>
			<li>Guatemala: <span>0800-888-523</span></li>
			<li>Mexico: <span>0800-888-523</span></li>
			<li>Panama: <span>0800-888-523</span></li>
			<li>Peru: <span>0800-888-523</span></li>
			<li>Venezuela: <span>0800-888-523</span></li>

		</ul>
	</div>
	
</div>