<?php ?>
<div class="container testimonios">
	
	<div class="left double-left">
		<p class="blue">Deja que ellas te cuenten<p>
		<p class="purple">Su experiencia, su vida, su crecimiento pueden decir mucho más<br/>
de lo que nosotros tengamos para contarte.</p>
	
	<div class="testi-wrapper">
		
		<div class="testi">
		<img src="<?php echo $this->getSkinUrl('images/testi_1.jpg') ?>" alt="" />
		<h3 class="testi-name">Antolina Silverio Bretón</h3>
		<h4 class="testi-job">Consultora Belcorp - República Dominicana</h4>
		<p class="testi-desc">Lorem ipsum dolor sit amet, te vix labore appetere conceptam, ne quo clita omnesque eloquentiam. <br/>Eu solet doming semper quo, nec vocibus postulant an. Qui te pertinax persecuti, ex pri hinc debet<br.>repudiare. An mei magna habeo utamur, qui in iusto delenit debitis. Facer voluptatibus no vix, per dicunt<br/><a class="seguir" href="#">Seguir leyendo...</a></p>
		</div>
		
		<div class="testi">
		<img src="<?php echo $this->getSkinUrl('images/testi_2.jpg') ?>" alt="" />
		<h3 class="testi-name">Sandra Landeo</h3>
		<h4 class="testi-job">Consultora Belcorp - Perú</h4>
		<p class="testi-desc">Lorem ipsum dolor sit amet, te vix labore appetere conceptam, ne quo clita omnesque eloquentiam. <br/>Eu solet doming semper quo, nec vocibus postulant an. Qui te pertinax persecuti, ex pri hinc debet<br.>repudiare. An mei magna habeo utamur, qui in iusto delenit debitis. Facer voluptatibus no vix, per dicunt<br/><a class="seguir" href="#">Seguir leyendo...</a></p>
		</div>
		
		<div class="testi">
		<img src="<?php echo $this->getSkinUrl('images/testi_3.jpg') ?>" alt="" />
		<h3 class="testi-name">Edelmira Ortiz Febus</h3>
		<h4 class="testi-job">Consultora Belcorp - Puerto Rico</h4>
		<p class="testi-desc">Lorem ipsum dolor sit amet, te vix labore appetere conceptam, ne quo clita omnesque eloquentiam. <br/>Eu solet doming semper quo, nec vocibus postulant an. Qui te pertinax persecuti, ex pri hinc debet<br.>repudiare. An mei magna habeo utamur, qui in iusto delenit debitis. Facer voluptatibus no vix, per dicunt<br/><a class="seguir" href="#">Seguir leyendo...</a></p>
		</div>
		
		<div class="testi">
		<img src="<?php echo $this->getSkinUrl('images/testi_4.jpg') ?>" alt="" />
		<h3 class="testi-name">Mercedes Cinelli Pérez</h3>
		<h4 class="testi-job">Consultora Belcorp - Costa Rica</h4>
		<p class="testi-desc">Lorem ipsum dolor sit amet, te vix labore appetere conceptam, ne quo clita omnesque eloquentiam. <br/>Eu solet doming semper quo, nec vocibus postulant an. Qui te pertinax persecuti, ex pri hinc debet<br.>repudiare. An mei magna habeo utamur, qui in iusto delenit debitis. Facer voluptatibus no vix, per dicunt<br/><a class="seguir" href="#">Seguir leyendo...</a></p>
		</div>
		<img style="margin-left:118px; margin-top:25px;" src="<?php echo $this->getSkinUrl('images/paginator.jpg') ?>" alt="" />
	</div>
		
	</div>
	<div class="right double-right">
		
		<h3>Testimonios Destacados</h3>
		<div class="mini-testi">
		<img src="<?php echo $this->getSkinUrl('images/mini-testi_1.jpg') ?>" alt="" />
		<h3 class="mini-testi-name">Antolina Silverio Bretón</h3>
		<h4 class="mini-testi-job">Consultora Belcorp - Bolivia</h4>
		<p class="mini-testi-desc">Lorem ipsum dolor sit amet, te vix labore appetere conceptam, ne quo clita omnesque eloquentiam.<br/><a class="seguir" href="#">Seguir leyendo...</a></p>
		</div>
		
		<div class="mini-testi">
		<img src="<?php echo $this->getSkinUrl('images/mini-testi_2.jpg') ?>" alt="" />
		<h3 class="mini-testi-name">Antolina Silverio Bretón</h3>
		<h4 class="mini-testi-job">Consultora Belcorp - El Salvador</h4>
		<p class="mini-testi-desc">Lorem ipsum dolor sit amet, te vix labore appetere conceptam, ne quo clita omnesque eloquentiam.<br/><a class="seguir" href="#">Seguir leyendo...</a></p>
		</div>
		
		<div class="mini-testi">
		<img src="<?php echo $this->getSkinUrl('images/mini-testi_3.jpg') ?>" alt="" />
		<h3 class="mini-testi-name">Antolina Silverio Bretón</h3>
		<h4 class="mini-testi-job">Consultora Belcorp - Venezuela</h4>
		<p class="mini-testi-desc">Lorem ipsum dolor sit amet, te vix labore appetere conceptam, ne quo clita omnesque eloquentiam.<br/><a class="seguir" href="#">Seguir leyendo...</a></p>
		</div>
		
		<div class="mini-testi">
		<img src="<?php echo $this->getSkinUrl('images/mini-testi_4.jpg') ?>" alt="" />
		<h3 class="mini-testi-name">Antolina Silverio Bretón</h3>
		<h4 class="mini-testi-job">Consultora Belcorp - Puerto Rico</h4>
		<p class="mini-testi-desc">Lorem ipsum dolor sit amet, te vix labore appetere conceptam, ne quo clita omnesque eloquentiam.<br/><a class="seguir" href="#">Seguir leyendo...</a></p>
		</div>

		
	</div>
	
</div>