<?php ?>
<div class="container testimonios">
	
	<div class="left double-left">
		<p class="blue">Antolina Silverio Bretón<p>
		<p class="detail-job">Consultora Belcorp - República Dominicana</p>
		
	
	
		
		<div class="testi">
		<div class="detail-testi">
		<img src="<?php echo $this->getSkinUrl('images/detail-testi_1.jpg') ?>" alt="" />
		<div class="detail-quote">“Gracias a Belcorp tuve la oportunidad
			de desarrollarme y apoyar a mi familia, sin dejar de dedicarme a los míos.</div>
		</div>	
		
		<p class="detail-testi-desc">Lorem ipsum dolor sit amet, te vix labore appetere conceptam, ne quo clita omnesque eloquentiam. <br/>Eu solet doming semper quo, nec vocibus postulant an. Qui te 		pertinax persecuti, ex pri hinc debet<br.>repudiare. An mei magna habeo utamur, qui in iusto delenit debitis. Facer voluptatibus no vix, per dicunt<br/><a class="seguir" href="#">Seguir 			leyendo...</a></p>
		
		<p class="detail-testi-desc">Lorem ipsum dolor sit amet, te vix labore appetere conceptam, ne quo clita omnesque eloquentiam. <br/>Eu solet doming semper quo, nec vocibus postulant an. Qui te 		pertinax persecuti, ex pri hinc debet<br.>repudiare. An mei magna habeo utamur, qui in iusto delenit debitis. Facer voluptatibus no vix, per dicunt<br/><a class="seguir" href="#">Seguir 			leyendo...</a></p>


		<p class="detail-testi-desc">Lorem ipsum dolor sit amet, te vix labore appetere conceptam, ne quo clita omnesque eloquentiam. <br/>Eu solet doming semper quo, nec vocibus postulant an. Qui te 		pertinax persecuti, ex pri hinc debet<br.>repudiare. An mei magna habeo utamur, qui in iusto delenit debitis. Facer voluptatibus no vix, per dicunt<br/><a class="seguir" href="#">Seguir 			leyendo...</a></p>


		<p class="detail-testi-desc">Lorem ipsum dolor sit amet, te vix labore appetere conceptam, ne quo clita omnesque eloquentiam. <br/>Eu solet doming semper quo, nec vocibus postulant an. Qui te 		pertinax persecuti, ex pri hinc debet<br.>repudiare. An mei magna habeo utamur, qui in iusto delenit debitis. Facer voluptatibus no vix, per dicunt<br/><a class="seguir" href="#">Seguir 			leyendo...</a></p>

		</div>
		
				
	
		
	</div>
	<div class="right double-right">
		
		<h3>Testimonios Destacados</h3>
		<div class="mini-testi">
		<img src="<?php echo $this->getSkinUrl('images/mini-testi_1.jpg') ?>" alt="" />
		<h3 class="mini-testi-name">Antolina Silverio Bretón</h3>
		<h4 class="mini-testi-job">Consultora Belcorp - Bolivia</h4>
		<p class="mini-testi-desc">Lorem ipsum dolor sit amet, te vix labore appetere conceptam, ne quo clita omnesque eloquentiam.<br/><a class="seguir" href="#">Seguir leyendo...</a></p>
		</div>
		
		<div class="mini-testi">
		<img src="<?php echo $this->getSkinUrl('images/mini-testi_2.jpg') ?>" alt="" />
		<h3 class="mini-testi-name">Antolina Silverio Bretón</h3>
		<h4 class="mini-testi-job">Consultora Belcorp - El Salvador</h4>
		<p class="mini-testi-desc">Lorem ipsum dolor sit amet, te vix labore appetere conceptam, ne quo clita omnesque eloquentiam.<br/><a class="seguir" href="#">Seguir leyendo...</a></p>
		</div>
		
		<div class="mini-testi">
		<img src="<?php echo $this->getSkinUrl('images/mini-testi_3.jpg') ?>" alt="" />
		<h3 class="mini-testi-name">Antolina Silverio Bretón</h3>
		<h4 class="mini-testi-job">Consultora Belcorp - Venezuela</h4>
		<p class="mini-testi-desc">Lorem ipsum dolor sit amet, te vix labore appetere conceptam, ne quo clita omnesque eloquentiam.<br/><a class="seguir" href="#">Seguir leyendo...</a></p>
		</div>
		
		<div class="mini-testi">
		<img src="<?php echo $this->getSkinUrl('images/mini-testi_4.jpg') ?>" alt="" />
		<h3 class="mini-testi-name">Antolina Silverio Bretón</h3>
		<h4 class="mini-testi-job">Consultora Belcorp - Puerto Rico</h4>
		<p class="mini-testi-desc">Lorem ipsum dolor sit amet, te vix labore appetere conceptam, ne quo clita omnesque eloquentiam.<br/><a class="seguir" href="#">Seguir leyendo...</a></p>
		</div>

		
	</div>
	
</div>