<?php ?>
<div class="container unete">
	
	<div class="left double-left">
		<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nec odio. Praesent libero. Sed cursus ante dapibus diam. Sed nisi. Nulla quis sem at nibh elementum imperdiet. Duis sagittis ipsum.</p>
		
	<div class="form-unete">
	<label>Nombre completo</label> 
	<input type="text" name="name" id="name"  autocomplete="off" tabindex="1" class="txtinput">
	<label>Documento de identidad</label> 
	<input type="text" name="name" id="dni"  autocomplete="off" tabindex="1" class="txtinput">
	<label>Teléfono</label> 
	<input type="text" name="name" id="telf"  autocomplete="off" tabindex="1" class="txtinput">
	<label>Correo electrónico</label> 
	<input type="text" name="name" id="email"  autocomplete="off" tabindex="1" class="txtinput">
	<label>País</label> 
	<input type="text" name="name" id="pais"  autocomplete="off" tabindex="1" class="txtinput">
	<label>Ingresa tu dirección</label> 
	<input type="text" name="name" id="direccion"  autocomplete="off" tabindex="1" class="txtinput">
	<a class="ubicar" href="#">Ubicar en el mapa</a>
	</div>	
	<div class="map-wrapper">	
		<iframe width="350" height="180" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.co.uk/maps?safe=off&amp;q=Av+Argentina,+Esperanza,+Santa+Fe,+Argentina&amp;ie=UTF8&amp;hl=en&amp;geocode=Fb3_H_4d7tFe_A&amp;split=0&amp;hq=&amp;hnear=Av+Argentina,+Esperanza,+Santa+Fe,+Argentina&amp;t=m&amp;z=14&amp;iwloc=A&amp;output=embed"></iframe><br /><small><a href="https://maps.google.co.uk/maps?safe=off&amp;q=Av+Argentina,+Esperanza,+Santa+Fe,+Argentina&amp;ie=UTF8&amp;hl=en&amp;geocode=Fb3_H_4d7tFe_A&amp;split=0&amp;hq=&amp;hnear=Av+Argentina,+Esperanza,+Santa+Fe,+Argentina&amp;t=m&amp;z=14&amp;iwloc=A&amp;source=embed" style="color:#0000FF;text-align:left">View Larger Map</a></small>
	</div>
	<a class="empieza" href="#">Empieza tu negocio</a>
	</div>
	
	<div class="right double-right">
		
		<h3>Contacto</h3>
		<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam. Sed nisi. Nulla quis sem at nibh elementum imperdiet. Duis sagittis ipsum.</p>
		<h4 class="phone">Lista de teléfonos de contácto</h4>
		<ul class="contact-list">
			<li>Argentina: <span>0800-888-523</span></li>
			<li>Bolivia: <span>0800-888-523</span></li>
			<li>Chile: <span>0800-888-523</span></li>
			<li>Colombia: <span>0800-888-523</span></li>
			<li>Costa Rica: <span>0800-888-523</span></li>
			<li>Dominicana: <span>0800-888-523</span></li>
			<li>Ecuador: <span>0800-888-523</span></li>
			<li>El Salvador: <span>0800-888-523</span></li>
			<li>Guatemala: <span>0800-888-523</span></li>
			<li>Mexico: <span>0800-888-523</span></li>
			<li>Panama: <span>0800-888-523</span></li>
			<li>Peru: <span>0800-888-523</span></li>
			<li>Venezuela: <span>0800-888-523</span></li>

		</ul>
	</div>
	
</div>